name: supagate-dev

services:
  supagate:
    build:              # 👈 Build from source
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - HEALTH_CHECK_TOKEN=${HEALTH_CHECK_TOKEN}
    env_file:
      - .env
    restart: unless-stopped