name: supagate

services:
  supagate:
    image: joebuildsstuff/supagate-app:latest
    container_name: supagate_app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default

networks:
  default: {}